### ISSUE TITLE
Unable to Alt+Tab to other applications in SuperPutty Full Screen Mode

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jimradford/superputty#486]
```
What steps will reproduce the problem?
1. Open a connection in SP
2. Go full Screen
3. Try to Alt+Tab to other windows application

What is the expected output? What do you see instead?
Expected: Alt+Tab should take me to the other app
Actual: SuperPutty still remains - behaves as if always on top - Note: Always 
on Top is not set when I checked this.

What version of the product are you using? On what operating system?
1.4.0.5

Please provide any additional information below.
OS: Windows 7  64bit
```

Original issue reported on code.google.com by `rt.in...@gmail.com` on 9 Dec 2014 at 6:53

**Comment by Chealer** [comment]
Regarding the issue(s) mentioned in the 2015-01-15 comment, see tickets #215 and #216 .

**Comment by jaceeeeee** [comment]
Hi, This specific issue has either never been an issue or solved in the current latest version as of October 19, 2022 (SuperPutty v1.4.10).  Please navigate through your menu bar in SuperPutty and click on the view tab to uncheck "Always on Top". This should have solved your inconvenience but if the issue still persists, you could open putty configuration, to your left you can find the tree view controls labeled as Category, go to the window node, expand it if necessary and click on Behaviour and make sure the option "Ensure window is always on top" is unchecked.

**Comment by wessven** [comment]
I can confirm that this issue still exists in SuperPuTTY 1.5.  "Always on Top" is disabled, and when not in full screen mode, it is not always on top.  But when I enter full screen mode, it remains "Always on Top", even if the option is disabled in the menu.

FWIW, I have a dual monitor setup, with the desktop extending over both screens.
